# 每12小时执行一次

name: Start

on:
   push:
   gollum:
   schedule:
       - cron: '30 */12 * * *'

jobs:
  TiebaSignIn:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
        BDUSS: ${{ secrets.BDUSS }}
      run: |
        mvn compile exec:java -Dexec.mainClass="top.srcrs.Run" -Dexec.args="${BDUSS}"
    - name: 'Send mail'
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: TieBa Report
        body: file://TiebaSignIn.txt
        to: steel_walker98@outlook.com
        from: GitHub Actions
        content_type: text/plain

